M-4: Switch from DataAnnotations to EntityTypeConfigurations
darkness-reveur/Trainee-modsen-task pull request #9
Opened 2022-03-30 20:11 UTC by darkness-reveur

2022-03-31 06:36 UTC, Rickstaper requested changes

2022-03-31 06:36 UTC, Rickstaper commented on MeetupPlatformApi/Context/EntitiesConfiguration/MeetupEntityConfiguration.cs
> +namespace MeetupPlatformApi.Context.EntitiesConfiguration
Use file scoped namespaces

2022-03-31 06:36 UTC, Rickstaper commented on MeetupPlatformApi/Context/EntitiesConfiguration/UserEntityConfiguration.cs
> +namespace MeetupPlatformApi.Context.EntitiesConfiguration
Use file scoped namespaces as well

2022-03-31 08:08 UTC, satma0745 commented on MeetupPlatformApi/Context/EntitiesConfiguration/UserEntityConfiguration.cs
> +                .HasColumnName("ux_users_username");
Why would You use index name convention for a column?

2022-03-31 12:48 UTC, Rickstaper requested changes

2022-03-31 13:30 UTC, satma0745 requested changes

2022-03-31 13:30 UTC, satma0745 commented on MeetupPlatformApi/Context/EntitiesConfiguration/MeetupEntityConfiguration.cs
> +            .HasColumnName("pk_meetups");
Why have You named `Id` column `pk_meetups`?

2022-03-31 13:30 UTC, satma0745 commented on MeetupPlatformApi/Context/EntitiesConfiguration/UserEntityConfiguration.cs
> +            .HasColumnName("pk_users");
Why have You named `Id` column `pk_users`?

2022-03-31 13:30 UTC, satma0745 commented on MeetupPlatformApi/Controllers/AuthenticationController.cs
>      public async Task<IActionResult> RegisterUser([FromBody] UserRegistrationDto userFromBody)
Please, rename DTO object to `registrationDto`

2022-03-31 16:21 UTC, satma0745 requested changes

2022-03-31 16:21 UTC, satma0745 commented on MeetupPlatformApi/Controllers/AuthenticationController.cs
> +        var existingUser = await context.Users.AnyAsync(exUser => exUser.Username == user.Username);
Please, do **not** use abbreviations in variable/parameter names (`exUser`)

2022-03-31 16:35 UTC, satma0745 approved these changes

2022-04-01 05:05 UTC, Rickstaper approved these changes

2022-04-01 09:41 UTC, Rickstaper requested changes

2022-04-01 09:41 UTC, Rickstaper commented on MeetupPlatformApi/Controllers/AuthenticationController.cs
> +        var usernameAlreadyTaken = await context.Users.AnyAsync(user => user.Username == user.Username);
You're comparing identical object instances.
Change one of them from user.Username to registrationDto.Username

2022-04-01 10:11 UTC, Rickstaper approved these changes

2022-04-01 12:20 UTC, merged